name = "MinIO KES Docs"
license = "Apache-2."
description = "Hugo theme made for MinIO KES Documentation"
homepage = "https://min.io/"
demosite = "https://min.io/"
tags = ["minio", "minio-documentation", "minio kes", "kes"]
min_version = "0.93.0"

[author]
    name = "Team MinIO"
    homepage = "https://min.io/"
