name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: npm-setup
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: npm-install-setup
      uses: bahmutov/npm-install@v1
      with:
        working-directory: ./themes/kes-docs-theme
        useLockFile: false

    - name: npm-build
      run: npm run build
      working-directory: ./themes/kes-docs-theme

    - name: hugo-install
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.138.0'
        extended: true

    - name: Build
      run: hugo

    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: assets
        compression-level: 9
        path: ./public/
      
    - name: Publish
      uses: burnett01/rsync-deployments@7.0.2
      with:
        path: ./public/
        switches:  --mkpath -rv --delete
        remote_path: ${{ secrets.DEPLOY_PATH }}/community/minio-kes
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
        remote_key_pass: ${{ secrets.DEPLOY_KEY_PASS }}